// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChannelBrowseFormController from "./channel_browse_form_controller"
application.register("channel-browse-form", ChannelBrowseFormController)

import MessageFilterController from "./message_filter_controller"
application.register("message-filter", MessageFilterController)

import MessageListStyleTabController from "./message_list_style_tab_controller"
application.register("message-list-style-tab", MessageListStyleTabController)

import MessagePeriodFormController from "./message_period_form_controller"
application.register("message-period-form", MessagePeriodFormController)

import MessageSearchFormController from "./message_search_form_controller"
application.register("message-search-form", MessageSearchFormController)

import SpeechesChartController from "./speeches_chart_controller"
application.register("speeches-chart", SpeechesChartController)
