version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 50
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    channel: "eslint-7"
  fixme:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
- config/
- db/
- test/
- vendor/
