language: ruby
rvm:
  - 2.3.1
  - 2.3.3
  - 2.4.0
services:
  - mysql
before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS log_archiver_test;'
notifications:
  irc:
    use_notice: true
    channels:
      - 'irc.trpg.net#irc_test'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
