language: ruby
dist: bionic
cache: bundler
rvm:
  # テストで使用するRubyのバージョンを指定する
  # 最新版とそのひとつ前のバージョンで試す
  # ただし、2.4 系列は Rails6.0 が動作対象外になるため、サポートしない
  - 2.5.6
  - 2.5.7
  - 2.6.4
  - 2.6.5
  - 2.7.0
services:
  - mysql
sudo: required
env:
  global:
    - TZ=Asia/Tokyo
    - CC_TEST_REPORTER_ID=LogArchiver
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - gem update --system
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - travis/install-mroonga.sh
  - sudo mysql -uroot < travis/create-mysql-user.sql
  - bundle install --jobs=3 --retry=3 --deployment --path=vendor/bundle
  - cp config/database.yml.travis config/database.yml
script:
  - bin/rails db:create RAILS_ENV=test
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  irc:
    use_notice: true
    channels:
      - 'irc.trpg.net#irc_test'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
addons:
  code_climate:
    repo_token: 74e589ede57e23f089cbbd2eee75be23a93b5ace7b5cfce58213cd3f21447147
