language: ruby
dist: bionic
cache: bundler
rvm:
  # テストで使用するRubyのバージョンを指定する
  # 最新版とそのひとつ前のバージョンで試す
  # ただし、2.4 系列は Rails6.0 が動作対象外になるため、サポートしない
  - 2.5.4
  - 2.5.5
  - 2.6.2
  - 2.6.3
services:
  - mysql
sudo: required
env:
  global:
    - TZ=Asia/Tokyo
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - gem update --system
install:
  - travis/install-mroonga.sh
  - sudo mysql -uroot < travis/create-mysql-user.sql
  - bundle install --jobs=3 --retry=3 --deployment --path=vendor/bundle
  - cp config/database.yml.travis config/database.yml
script:
  - bin/rails db:create RAILS_ENV=test
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails test
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  irc:
    use_notice: true
    channels:
      - 'irc.trpg.net#irc_test'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
addons:
  code_climate:
    repo_token: 74e589ede57e23f089cbbd2eee75be23a93b5ace7b5cfce58213cd3f21447147
