language: ruby
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.3
services:
  - mysql
sudo: required
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get install -y -V mysql-server-mroonga
before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -u root -e 'SET GLOBAL innodb_file_format = Barracuda'
  - mysql -u root -e 'SET GLOBAL innodb_file_per_table = 1'
  - mysql -u root -e 'SET GLOBAL innodb_large_prefix = 1'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS log_archiver_test;'
notifications:
  irc:
    use_notice: true
    channels:
      - 'irc.trpg.net#irc_test'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
