language: ruby
dist: bionic
cache: bundler
rvm:
  - 2.6.4
services:
  - mysql
sudo: required
env:
  global:
    - TZ=Asia/Tokyo
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - gem update --system
install:
  - travis/install-mroonga.sh
  - sudo mysql -uroot < travis/create-mysql-user.sql
  - bundle install --jobs=3 --retry=3 --deployment --path=vendor/bundle
  - cp config/database.yml.travis config/database.yml
  - wget http://dev.cre.ne.jp/log-archiver_dump.tar.gz
  - tar -xvf log-archiver_dump.tar.gz
script:
  - bin/rails db:create
  - bin/rails db:migrate
  - bin/rails db:seed
  - bin/rails data:channels:prepare_irc_cre_jp
  - travis/import.sh
