name: Test and coverage measurement

on:
  push:
    paths-ignore:
      - doc/**
      - README.md
  pull_request: {}

jobs:
  test:
    name: "Ruby 3.3: test and coverage measurement"
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    env:
      RAILS_ENV: test
      TZ: Asia/Tokyo
    services:
      db:
        image: groonga/mroonga:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 33060:3306
      redis:
        image: redis:6
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'
          cache: 'yarn'
      - name: Compile JavaScripts (webpack)
        run: |
          yarn install
          NODE_ENV=production bin/yarn webpack
      - name: Setup database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:setup
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 74e589ede57e23f089cbbd2eee75be23a93b5ace7b5cfce58213cd3f21447147
        with:
          coverageCommand: bin/rails test
