name: Test Log Archiver

on:
  - push
  - pull_request

jobs:
  test:
    name: Test Log Archiver
    strategy:
      matrix:
        ruby:
          # 安定するまで1バージョンのみで実行する
          # - 2.5
          # - 2.6
          - 2.7
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      TZ: Asia/Tokyo
    services:
      db:
        image: groonga/mroonga:latest
        ports:
          - 33060:3306
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 3 --retry 3
      - name: Setup database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create
          bin/rails db:migrate
      - name: Run tests
        run: |
          bin/rails test
